# Generated by Django 5.0.6 on 2024-07-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_profile_homepage_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
