# Generated by Django 5.0.6 on 2024-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_rename_homepage_link_profile_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
