# Generated by Django 5.0.6 on 2024-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_alter_profile_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
